/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#e7bea5",
        "primary-fixed": "#ffdcc6",
        "surface-bright": "#fff9ed",
        "on-primary-fixed-variant": "#5d412d",
        "on-error-container": "#93000a",
        "surface-tint": "#775843",
        "secondary-fixed": "#ffdcc4",
        "error-container": "#ffdad6",
        "surface-variant": "#e9e2d3",
        "on-tertiary-fixed-variant": "#643f00",
        "surface-container-low": "#faf3e4",
        "on-primary-fixed": "#2c1607",
        "on-secondary-container": "#7a502f",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d3c3bb",
        "surface-container": "#f4edde",
        "surface-container-high": "#eee8d9",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#e0d9cb",
        "background": "#fff9ed",
        "tertiary-container": "#613d00",
        "on-tertiary-fixed": "#2a1800",
        "inverse-on-surface": "#f7f0e1",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffddb5",
        "on-surface": "#1e1b13",
        "on-secondary-fixed": "#2f1400",
        "surface-container-highest": "#e9e2d3",
        "primary": "#412817",
        "outline": "#82746d",
        "surface": "#fff9ed",
        "secondary-fixed-dim": "#f3bb92",
        "on-secondary-fixed-variant": "#643e1f",
        "on-tertiary-container": "#e1a758",
        "inverse-surface": "#333026",
        "secondary-container": "#ffc69c",
        "secondary": "#7f5534",
        "on-background": "#1e1b13",
        "primary-container": "#5a3e2b",
        "inverse-primary": "#e7bea5",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#50453e",
        "on-secondary": "#ffffff",
        "on-primary-container": "#d1aa91",
        "tertiary": "#432900",
        "tertiary-fixed-dim": "#f8bb6a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-xl": "2rem",
        "margin-lg": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "1.25rem",
        "gutter": "1rem",
        "gutter-sm": "0.75rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "headline-md": ["Thmanyah", "Noto Serif", "serif"],
        "title-md": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "body-md": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "headline-lg": ["Thmanyah", "Noto Serif", "serif"],
        "label-md": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "label-lg": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "label-sm": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "display-lg": ["Ballet", "Noto Serif", "serif"],
        "body-sm": ["Thmanyah", "IBM Plex Sans Arabic", "sans-serif"],
        "headline-sm": ["Thmanyah", "Noto Serif", "serif"],
        "thmanyah": ["Thmanyah", "sans-serif"],
        "ballet": ["Ballet", "serif"]
      },
      fontSize: {
        "body-lg": ["17px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["26px", { lineHeight: "38px", letterSpacing: "0", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "500" }],
        "display-lg": ["34px", { lineHeight: "48px", letterSpacing: "0", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
};
